version: "3.9"
services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=goosechase
      - POSTGRES_PASSWORD=canadensis
      - POSTGRES_DB=postgres
    restart: always
